### ISSUE TITLE
Folder permission issue

### ISSUE THREAD

**Issue by shyamsalimkumar** [SublimeText/AdvancedNewFile#107]
So I created a folder with a file inside it.

```
asd/
`-- asd.asd
```

They had the following permissions

```
shyam@shyam-desktop:~/test$ ls -al asd/
total 8
drwxrwxrwx 2 shyam shyam 4096 Aug 25 22:37 .
drwxrwxr-x 7 shyam shyam 4096 Aug 25 22:37 ..
-rw-rw-rw- 1 shyam shyam    0 Aug 25 22:37 asd.asd
```

Isn't that strange that it assumes folders have to be executable? Also in the package defaults `"folder_permissions": ""` and `"file_permissions": ""` they are both the same. I have no user settings for this package. So why is it setting folders to be executable?

One time I got an issue with deletion of folders is that when I try to delete the folder I am unable to. I can do this easily with **ST3**, but on the terminal I need to use `sudo`. This happens randomly. There was no issue in the above example but for the below folder structure I got an error. Is this a **Linux** thing?

```
shyam@shyam-desktop:~/test$ tree asdasd/
asdasd/
`-- asdasd
    `-- asdasd
        `-- asdf.js
2 directories, 1 file
shyam@shyam-desktop:~/test$ rm -rf asdasd/
rm: cannot remove ‘asdasd/asdasd’: Permission denied
shyam@shyam-desktop:~/test$ sudo rm -rf asdasd/
shyam@shyam-desktop:~/test$
```

Then I added the following User settings

```
{
    "folder_permissions": "644",
    "file_permissions": "644"
}
```

But then I could not create folders inside folders inside folders. It went one level and popped an error.
`as/asd/asdf/asdfg` resulted in `as/asd` where `asd` is a folder. Again is this a **Linux** error?

**Comment by kumarharsh** [comment]
@skuroda I think a more sensible default should be given to the users, instead of a 0777 for files/folders. Most unsuspecting users will not care to fish out this issue, and figure out what's going on. They'll just leave ST3 and for got Atom (as a few friends did) or uninstall ANF.

Please make the file and folder permissions set to a more sensible default.

**Comment by skuroda** [comment]
@kumarharsh, I apologize for the confusion. As I said before, I inherited the plugin with that used those default permissions, and I do not plan on changing it. That being said, I believe folders are the only items created with 777 permissions. When I tested, files were created with 644 I believe. Was that not the case for you?

**Comment by kumarharsh** [comment]
@skuroda I understood what you're trying to say, but this is what I'm saying: You've inherited the plugin, so you are going to fix bugs, etc in the plugin, right? Well, this one is a bug (not having a **sensible default** can be a big problem, as anyone with a Windows 8 desktop, where people were taken to the metro-ui by default, can vouch for). I believe you can correct that now. Maybe contact the original author to get their view, but I think it should be done.

**Comment by skuroda** [comment]
@kumarharsh, I understand, but the other issue is that according to the python docs, the mode specified is not always respected. While I honestly don't know what systems it isn't supported on, it's still something worth taking note about. Wouldn't it be more confusing if I said the permissions were configured a particular way, but then they came up as something different? For situations where it does matter, I added `folder_permissions` and `file_permissions` so end users can set up the defaults in the way that works best for them. Perhaps I should have been more explicit in the README and install message about this particular issue, as permissions are important. But, along those lines, I would guess that many people simply don't read these.
