### ISSUE TITLE
Suddenly Stopped Working on Sublime 3

### ISSUE THREAD

**Issue by golamSaroar** [SublimeText/AdvancedNewFile#168]
AdvancedNewFile was working just fine in my Sublime Text 3 until it suddenly stopped working a few days ago.. When I click **ctrl+alt+n** or select _New File_ from sidebar, a black section appears at the bottom which is blank.. Previously, I could enter my file name in that section but now it's just blank.. No scope for me to do anything except pressing Esc so that I can get rid of this annoying section.. What's wrong with it?

**Comment by golamSaroar** [comment]
![captured](https://cloud.githubusercontent.com/assets/14212503/25988827/5d6a370c-371b-11e7-9e9e-9c1243b6ce88.PNG)

This is what I get when I press ctrl+alt+n ..

**Comment by n1crack** [comment]
same here..

**Comment by skuroda** [comment]
Odd, I haven't changed this plugin in quite awhile. What version of ST3 are you using @golamSaroar?

**Comment by ALEXMORF** [comment]
I have the same issue with all plugins that shows a bottom prompt, including AdvancedNewFile and ShellComamnd. I have Material Theme activated, and my ST3 version is Build 3126.

**Comment by ALEXMORF** [comment]
I actually found the cause. Just as I suspected, Material Theme has a conflict with all plugins that prompts such input bars. See [#67](https://github.com/equinusocio/material-theme/issues/67) issue on Material Theme's git repository. 

Solution is simple, just drag it up and then drag it down. It's not ideal and definitely needs some fix, though.

**Comment by FichteFoll** [comment]
As mentioned, this is a theme issue and not related to ANF.
