### ISSUE TITLE
can we disable opening file when right click at sidebar?

### ISSUE THREAD

**Issue by videni** [SublimeText/AdvancedNewFile#177]

**Comment by skuroda** [comment]
That is a function of the Sublime Text editor, rather than this plugin. I'd recommend reaching out via https://forum.sublimetext.com.

**Comment by FichteFoll** [comment]
You can by changing the `preview_on_click` setting in your normal ST preferences. Since a while ago (don't remember when), the  setting also accepts the value `"only_left"` to keep the preview on left clicks but prevent it for right clicks.
