### ISSUE TITLE
[feature] add create new folder at cwd 

### ISSUE THREAD

**Issue by alexzanderr** [SublimeText/AdvancedNewFile#184]
I just want to create a new folder at cwd just like I create a new file at cwd (like using File Manager: New file, but `File Manager: New Folder`)

**Comment by skuroda** [comment]
Hi,

Thank you for creating the ticket. Unfortunately I don't actively maintain
this plugin anymore. You're more than welcome to contribute a PR and I'll
get it merged in though.

You may want to additionally see if
https://packagecontrol.io/packages/FileManager fulfills your use case.

Scott

**Comment by alexzanderr** [comment]
i already had file manager installed, it doesnt have create new folder command, i've looked into it.

btw, your plugin is very good because it can create a file at the cwd of the current opened buffer, and for me its absolutely great.

**Comment by rchl** [comment]
File Manager can create a new folder and it can create at cwd (if by `cwd` you mean the directory of the current file).
Can create a keybinding like:

```js
{
        "keys": ["alt+n"],
        "command": "fm_create",
        "args": {"initial_text": "$here/"},
}
```

and if your input ends with `/` then it will create a directory.

**Comment by alexzanderr** [comment]
> if by cwd you mean the directory of the current file

wrong.

it creates at the root of the project opened in sublime no matter how deep you are in the folders.

**Comment by rchl** [comment]
It supports various aliases that you can use instead of `$here`. For example `$folder` is what should point at the root of the project (actually first folder in the project as there is no concept like root of the project). But it should also do the same by default with no `initial_text` defined.

**Comment by alexzanderr** [comment]
`$here` doesnt expand to anything, it remains `$here`

> For example $folder is what should point at the root of the project

I didnt want root of the project. I said `cwd` of the current file opened and focused in sublime text.

**Comment by FichteFoll** [comment]
You mean like creating a new file in the same directory as the currently active file works for "AdvancedNewFile: New File" when starting the file name with `./`?

ANF in general doesn't have the functionality to create folders (yet). What use case do you have in mind where the existing "New File" command that creates all non-existant parent folders prior to the file path that was entered?

**Comment by rchl** [comment]
> `$here` doesnt expand to anything, it remains `$here`

- The project root is `/usr/local/workspace/github/volar/`
- Currently opened files is `/usr/local/workspace/github/volar/packages/vue-language-service/package.json`
- `fm_create` command works like this in those two cases:

`$here` expands to the base directory of currently open file:
<img width="528" alt="Screenshot 2022-07-19 at 19 56 05" src="https://user-images.githubusercontent.com/153197/179817832-b57c3c30-3666-4211-9674-27c638c8b977.png">

`.` resolves to project root:
<img width="343" alt="Screenshot 2022-07-19 at 19 56 42" src="https://user-images.githubusercontent.com/153197/179817853-3d6b25ae-f967-4618-b9bb-da9f39ea1305.png">

**Comment by rchl** [comment]
Yes. It should be clear from the context that started at https://github.com/SublimeText/AdvancedNewFile/issues/184#issuecomment-1130035268 but since the replies are months apart the context might have been lost maybe :)

**Comment by FichteFoll** [comment]
Well, turns out you can already create folders with this plugin by ending the file name with a slash, so the following would create a folder named "test" next to the currently active file: `./test/`.

Closing as invalid since it's already supported. Alas, this package needs better documentation/README.

**Comment by alexzanderr** [comment]
> > `$here` doesnt expand to anything, it remains `$here`
> 
> Did you look at the status bar to see the expanded path?
> 
>     * The project root is `/usr/local/workspace/github/volar/`
> 
>     * Currently opened files is `/usr/local/workspace/github/volar/packages/vue-language-service/package.json`
> 
>     * `fm_create` command works like this in those two cases:
> 
> 
> `$here` expands to the base directory of the currently open file: <img alt="Screenshot 2022-07-19 at 19 56 05" width="528" src="https://user-images.githubusercontent.com/153197/179817832-b57c3c30-3666-4211-9674-27c638c8b977.png">
> 
> `.` resolves to the project root: <img alt="Screenshot 2022-07-19 at 19 56 42" width="343" src="https://user-images.githubusercontent.com/153197/179817853-3d6b25ae-f967-4618-b9bb-da9f39ea1305.png">

this solves everything, thanks a lot guys for help, sorry to bother for such stupid issue.
