### ISSUE TITLE
Going up the folder tree

### ISSUE THREAD

**Issue by shyamsalimkumar** [SublimeText/AdvancedNewFile#48]
As mentioned [here](https://github.com/skuroda/Sublime-AdvancedNewFile/issues/9#issuecomment-23120602), `:` can be used to make a file in the same folder. But it is currently not possible to go up the tree. Or at least I'm unaware as to how this can be achieved.

And it would be nice to use something like the default `.` to indicate the current folder and `..` to indicate the parent folder rather than `:`.

**Comment by thebarefootdev** [comment]
':'  at the beginning does not work as expected on Mac
